### PR TITLE
Python2 to Python3 conversion

### PR DESCRIPTION
**Pull request by tasleson**
@vpodzime Please try this branch out and see if it works for you.  Unit tests appear to pass on my F23 system, thanks!

### CODE REVIEW

**Comment by vpodzime** [comment]
Seems to be working great. I think this can be merged and if I find something with my tests (I'll soon start running libblockdev's tests with the dbus plugin), we can fix it later.

**Comment by vpodzime** [comment]
Or not, there seems to be an issue with `gobject`.

**Comment by vpodzime** [comment]
```
LVMError: Failed to call the 'Resize' method on the '/com/redhat/lvmdbus1/Lv/5' object: GDBus.Error:org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/home/koki/sources/lvm-dubstep/lvmdbus/lv.py", line 383, in Resize
    resize_options), cb, cbe, return_tuple=False)
  File "/home/koki/sources/lvm-dubstep/lvmdbus/request.py", line 47, in __init__
    self.timer_id = gobject.timeout_add_seconds(
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 64, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by vpodzime** [comment]
I think `GLib` should now be used. It provides a main loop and things like that. It doesn't provide `threads_init()`, but that should no longer be called (it's done automatically).

**Comment by tasleson** [comment]
This was because of missing a import gobject in request.py.  I'm not sure why I missed it because the unit test does indeed fail.  I fixed this up and the unit tests are running correctly.

We can certainly look into converting over to GLib.

**Comment by tasleson** [comment]
Picked commits individually and applied to master to avoid a messy merge history.

**Pull request closed without merging**
